api_platform:
    title: Domain Watchdog API
    version: 1.0.0
        
    formats:
        jsonld: [ 'application/ld+json' ]
        xml: [ 'application/xml' ]
        json: [ 'application/json' ]
        text: [ 'text/calendar' ]
    docs_formats:
        jsonld: [ 'application/ld+json' ]
        jsonopenapi: [ 'application/vnd.openapi+json' ]
        html: [ 'text/html' ]
    defaults:
        stateless: true
        cache_headers:
            vary: [ 'Content-Type', 'Authorization', 'Origin' ]
        pagination_client_items_per_page: true
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    show_webby: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

